# Generated by Django 4.2.8 on 2023-12-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.TextField(choices=[("editor", "Editor"), ("writer", "Writer")], default="editor"),
        ),
    ]
