# Generated by Django 4.2.8 on 2023-12-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_alter_company_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="companies"),
        ),
    ]
